# Generated by Django 5.2.11 on 2026-04-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodinventor', '0003_alter_bloodrequest_doctor'),
        ('medicalOfficers', '0003_remove_doctorprofile_user_doctor_doctormessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
