# Generated by Django 5.2.10 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_bloodcamp_campregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetails',
            name='last_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
