# Generated by Django 5.2.11 on 2026-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_alter_user_is_staff_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'donor'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('Inventor', 'Inventor')], default='donor', max_length=10),
        ),
    ]
