# Generated by Django 5.2.11 on 2026-04-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodinventor', '0002_bloodinventory_temperature_bloodrequest_and_more'),
        ('medicalOfficers', '0003_remove_doctorprofile_user_doctor_doctormessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='medicalOfficers.doctor'),
        ),
    ]
