# Generated by Django 5.2.10 on 2026-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodinventor', '0003_alter_bloodrequest_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='priority_level',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
